---
title: "Features and Objectives of Acute Internal Medicine"
description: |
  Acute internal medicine in Malaysia.
site: distill::distill_website
---

Like established subspecialties palliative care, geriatrics, oncology, and intensive care, to name but a few, Acute Internal Medicine has a functional basis rather than organ based.


Acute internal medicine is a model of care in which patients with acute medical illness are provided with the best quality care, in the right environment, with assessment, diagnosis and treatment as actively managed components of that care.


## The key features of AIM are:


* clinical service delivered by acute physicians within the AMU environments for at least 12 hours per day and seven days per week
* medical leadership within an AMU in a service designed and managed by acute physicians who specialise in AIM
* service delivered by an AIM physician and dedicated multidisciplinary team with timely and appropriate interaction with other specialties
* service design informed by quality standards
* performance benchmarked against key clinical quality indicators for AMU.


## The objectives of AIM are:

* To provide immediate and effective patient-centered care to the acute and complex undifferentiated cases, with timely and appropriate interaction with other specialties.
* To provide high standard specialist care to the acute and complex undifferentiated cases, both at the earliest presentation to the hospital and in the critical care settings.
* To enhance and strengthen the provision of care in a multidisciplinary team approach, preventing fragmentation of patient care.
* To be the backbone in the provision of quality specialist care to the general medical patients.


## Role of AAIM physician 

* Pre admission: 
  + AIM physician working in M.A.U, Emergency department, Daycare, and specialist clinic

* Acute care: 
  + AIM physician working in critical care areas, i.e HDW, CCU, CRW

* Advanced care:
  + AIM physician working in general medical wards


There are 3 main components to the services provided by the AIM physician:

* Inpatient services
* Outpatient services
* Referral services


## Inpatient Services 

* Critical Care Units (CCU/CRW/HDW)
* Medical Admissions Unit (MAU)


### Medical Admissions Unit (MAU)

MAU provides service to the short stay patients within the department of medicine, with expected length of stay of 24-72 hours.

* Objectives:

> To provide safe and effective immediate care to medical patients, within the first 24-72 hours of presentation.

> To reduce patient length of stay by utilizing appropriate alternative pathways to  deliver high standards of care (i.e FAST clinic).

* Structure:

 	The MAU ward is headed by the Acute Internal Medicine consultants, assisted by an MAU ward Manager, ideally a nursing sister trained or experienced in acute medical care. The ward is preferably located near the emergency department with easy access to support services frequently required by the patients admitted to the unit, such as radiology services, laboratory, endoscopy unit, operation theater and others. The bed strength of an MAU will be dependent on the needs of the hospital, and may be a flexi/mixed gender ward (male & female). Being an admissions unit, MAU shall have a close working relationship with the hospital bed manager.


## Outpatient Services 
 
### Fast Clinic (Rapid Review Clinic)

* Objectives:

> To provide high quality rapid access to outpatient services for patients presenting to the emergency department, not requiring admission but require early outpatient review and treatment.

> To improve utilisation of acute medical beds by providing early continuity of care as outpatient, for discharged medical patients.

> To provide efficient outpatient care for treatment/procedures that would have otherwise been performed as inpatient, i.e daily outpatient IV therapy etc.

* Structure

The clinic is under the direct supervision of the Acute Internal Medicine consultant and assisted by an MAU Clinic Manager, ideally a nursing sister trained or experienced in acute medical care. A Staff Nurse shall be in charge of arranging patient appointments and outpatient care plans. Staff strength will depend on patient volume and complexity of cases. The clinic shall operate during office hours of 08:00 to 17:00, Mondays to Fridays. Access to the clinic is by referral to the MAU team, mainly from the emergency department, for medical patients who do not require immediate inpatient care, but early clinic review is essential.

* Facilities

Such Clinic is equipped with 1 examination room, with office infrastructure and one examination trolley.

## Referrals

### MAU mobile referral team

* Objectives:

> To provide immediate safe and high standard of care to medical patients presenting to the emergency department by establishing early accurate diagnosis and initiating early treatment.   

> To improve early patient-centered specialist care, and prevent unnecessary or inappropriate admissions.

 
<br></br>

*Section authors: Dr Siti Zulfa Zulkifli, Dr Azahirafairud Abdul Rahim & Dr Saiful Safuan Md Sani*
