---
title: "Daily Effective Reproduction Number"
description: |
  Quick take on the COVID-19 pandemic progress in Malaysia.
author:
  - name: Dr Saiful Safuan Md Sani 
    url: https://saifulsafuan.com
    affiliation: Advanced Acute Internal Medicine Society Malaysia & Department of Medicine Hospital Kuala Lumpur
    affiliation_url: https://aaims.co
date: "`r Sys.Date()`"
output: 
  distill::distill_article:
    self_contained: yes
    toc: yes
    toc_depth: 2
---
```{r message=FALSE, echo=FALSE, warning=FALSE}
library(knitr)
library(distill)
library(googlesheets)
library(gsheet)
library(dplyr)
library(incidence)
library(ggplot2)
library(plotly)
library(EpiEstim)
library(earlyR)
library(tidyr)
library(lubridate)
library(ggformula)
library(ggthemes)
```
```{r message=FALSE, echo=FALSE, warning=FALSE}
url <- 'https://docs.google.com/spreadsheets/d/1jLn3UoJBfusBcEbLS8n8oPBJd6bUiA0WMqZ7LHNkdjw/edit?usp=sharing'
data <- gsheet2tbl(url)
data <- data %>% slice(3:nrow(data))
```

```{r message=FALSE, echo=FALSE, warning=FALSE}
## we choose to draw:
## - the mean of the SI in a Normal(3.96, 1), truncated at 1 and 21
## - the sd of the SI in a Normal(4.75, 0.5), truncated at 0.5 and 7.5
config <- make_config(list(mean_si = 3.96, std_mean_si = 0.5,
                           min_mean_si = 3.5, max_mean_si = 4.5,
                           std_si = 4.75, std_std_si = 0.5,
                           min_std_si = 4.5, max_std_si = 5.1))
# https://drive.google.com/file/d/1HQex9HFdNy883zTiUEywsBiFEb_orr2t/view   

res_uncertain_si <- estimate_R(data$dailynew,
                               method = "uncertain_si",
                               config = config)
#> Default config will estimate R on weekly sliding windows.
#>     To change this change the t_start and t_end arguments.
```

```{r, fig.cap="Click on the chart to engage its interactive mode. *Ribbon:* 95% CI of the mean $R_e$.", out.extra="class=external",  fig.width=8, fig.height=4, message=FALSE, echo=FALSE, warning=FALSE}
dfp55 <- data.frame(res_uncertain_si$R)
dfp55$time <- data$date[8:length(data$date)]
dfp55 <- dfp55 %>% select(time, Mean.R., Quantile.0.025.R., Quantile.0.975.R.)
colnames(dfp55) <- c("Time", "Mean_R", "Quantile_0.025", "Quantile_0.975")

p55 <- ggplot(dfp55, aes(Time,Mean_R))
p55<- p55+ geom_line(col = "steelblue")
p55<- p55+ geom_ribbon(aes(ymin=Quantile_0.025,ymax=Quantile_0.975), alpha=0.3, fill = "steelblue") +
  labs(y = "R", x = "Time", title = "Daily Effective Reproduction Number") + 
  theme_fivethirtyeight()
ggplotly(p55) %>%
  layout(title = list(text = paste0('Daily R<sub>e</sub>',
                                    '<br>',
                                    '<sup>',
                                    'Serial interval adjusted for uncertainty',
                                    '</sup>')))
```

The COVID-19 pandemic in Malaysia will only die out if the effective reproduction number, $R_e$, remains below zero.
